# -*- coding: utf-8 -*-
"""dashboard5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHbEq46DPDHOK9c5Y1ySz7tc9UStomiY
"""

#pip install streamlit

#pip install babel

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency

sns.set(style='dark')

# prompt: buat multi select by tahun 2016, 2017,2018 bisa pilih salah satu atau smeuanya


st.set_page_config(page_title="Brazilian E-commerce Dashboard",
                   page_icon=":bar_chart:", layout="wide")

# --- HIDE STREAMLIT STYLE ---
hide_st_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            </style>
            """
st.markdown(hide_st_style, unsafe_allow_html=True)


# --- LOAD DATAFRAME ---
try:
    all_df = pd.read_csv("all_data.csv")
except FileNotFoundError:
    st.error("The 'all_data.csv' file was not found. Please upload the file.")
    st.stop()  # Stop execution if file is not found

# --- SIDEBAR ---
with st.sidebar:
    # Add a logo image (replace 'logo.png' with your actual logo file)
    st.image('Brazilianlogo.png')  # Adjust width as needed

    # Multiselect for years
    selected_years = st.multiselect(
        "Select Year(s)",
        options=[2016, 2017, 2018],
        default=[2016, 2017, 2018]  # Set default to all years
    )



# --- FILTERING DATA ---
# Convert 'order_purchase_timestamp' to datetime objects if not already
if not pd.api.types.is_datetime64_any_dtype(all_df['order_purchase_timestamp']):
    all_df['order_purchase_timestamp'] = pd.to_datetime(all_df['order_purchase_timestamp'])

# Extract year for filtering
all_df['year'] = all_df['order_purchase_timestamp'].dt.year

# Filter the dataframe based on selected years
main_df = all_df[all_df['year'].isin(selected_years)]


# ... rest of your dashboard code (using the filtered 'main_df')

st.sidebar.header("Conclusion 2016-2018")
st.sidebar.markdown("""
1. 10 produk dengan jumlah penjualan terbanyak dalam periode 2016-2018, yaitu: bed_bath_table, furniture_decor,health_beauty, sports_leisure, computers_accessories, housewares, watches_gifts, garden_tools,telephony, auto.
 Produk terlaris didominasi produk rumah tangga dan dekorasi. Selain itu, health_beauty dan sports_leisure juga memiliki permintaan tinggi.

2. 10 Kota dan state yang memiliki pelanggan terbanyak pada 2016-2018, yaitu: Sao Paulo, Rio de Janeiro, Belo Horizonte, Brasilia, Curitiba, Campinas, Porto Alegre, Salvador, Guarulhos, Sao Bernardo do Campo

3. Tren jumlah transaksi dan total penjualan dari tahun 2016 hingga 2018:
- Tren transaksi penjualan terjadi pertumbuhan signifikan sejak 2017, mencapai puncaknya pada akhir 2017, dengan puncak tertinggi pada bulan November 2017.
- Tren total penjualan(revenue) menunjukkan pertumbuhan stabil hingga di akhir 2017, puncak pada bulan November 2017.

4. Penjual dengan total revenue tertinggi selama 2016-2018, berada di daerah guariba city, State of Sao Paulo dengan seller_id '4869f7a5dfa277a7dca6462dcf3b52b2'. Penjual tersebut memiliki kategori produk terlaris yaitu : Auto, Watches & Gifts
, Health & Beauty, Cool Stuff, Computers Accessories, Electronics, Audio, Sports & Leisure, Telephony, Consoles & Games dengan total revenue 229472.63.

5. Berdasarkan analisis teks dari ulasan pelanggan tahun 2016-2018, komentar  yang paling sering disebut dalam ulasan yaitu kata-kata seperti "Muito bom" (Sangat baik), "Bom" (Baik), "Ótimo" (Luar biasa), dan "Recomendo" (Saya rekomendasikan)

6. analisis RFM untuk mengidentifikasi pelanggan yang VIP, Loyal, At Risk to Churn, dan Churn berdasarkan transaksi terakhir menunjukkan bahwa:
-  VIP Customers adalah pelanggan dengan transaksi terbaru, sering berbelanja, dan memiliki nilai transaksi tinggi. Mereka harus dijaga dengan program eksklusif.
- Loyal Customers sering berbelanja tetapi mungkin tidak dalam waktu dekat. Penawaran khusus dapat meningkatkan keterlibatan mereka secara berlanjut.
- At Risk to Churn adalah pelanggan yang dulunya aktif tetapi mulai jarang berbelanja. Strategi re-engagement diperlukan untuk menarik mereka kembali.
- Churned Customers tidak bertransaksi dalam waktu lama. Promosi khusus atau diskon besar bisa menjadi cara untuk mengaktifkan mereka kembali.
- Sao Paulo dan Rio de Janeiro memiliki jumlah churn tertinggi
- Churn pada tahun 2017- 2018 cukup tinggi.
- Churn customer mendominasi dengan 59.9%, menunjukkan bahwa lebih dari setengah pelanggan telah berhenti menggunakan layanan.
""")

st.markdown(
    """
    Hello, C - Level ! :smile: :wave:
    """
)
st.header('Brazilian E-Commerce Dashboard :bar_chart:')
#
st.markdown("---")

df = pd.read_csv('all_data.csv')
#df.head()

# prompt: streamlit buat 6 kolom, datanya dari all_data.csv. tampilin:
# 1. Total Customer
# 2. Total Seller
# 4. Total Transaksi
# 5. Total Revenue
# 6. Rata rata rate by score review

import pandas as pd
import streamlit as st

# Assuming 'main_df' is your filtered dataframe from the previous code

# Calculate the required metrics
total_customers = main_df['customer_unique_id'].nunique()
total_sellers = main_df['seller_id'].nunique()
total_transactions = len(main_df)
total_revenue = main_df['price'].sum()

# Format total revenue using babel.numbers.format_currency
formatted_revenue = format_currency(total_revenue, 'R$', locale='pt_BR')  # Use 'BRL' for Brazilian Real and 'pt_BR' locale


# Create columns using st.columns
col1, col2, col3, col4 = st.columns(4)

# Display metrics in each column
col1.metric("Total Customers", total_customers)
col2.metric("Total Sellers", total_sellers)
col3.metric("Total Transactions", total_transactions)
col4.metric("Total Revenue (R$)", total_revenue)
#col5.metric("Average Review Score", average_review_score)
# Add an empty column for better layout

# prompt: streamlit top 10 best selling products yang bisa ke filter sesuai tahun yang dipilih.


# --- TOP 10 BEST SELLING PRODUCTS ---
st.subheader("Top 10 Best Selling Products")

# Calculate top 10 products
top_products = main_df.groupby('product_category_name_english')['order_id'].count().sort_values(ascending=False).head(10)

# Create figure and axes
fig, ax = plt.subplots(figsize=(16, 6))

# Create the bar plot using seaborn
sns.barplot(y=top_products.index, x=top_products.values, ax=ax)
ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
ax.set_xlabel('Product Category')
ax.set_ylabel('Number of Orders')
ax.set_title(f'Top 10 Best Selling Products ({", ".join(map(str, selected_years))})')

# Display the plot in Streamlit
st.pyplot(fig)

# --- CHARTS ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("Top 10 Cities by Customers")
    top_cities = main_df.groupby('customer_city')['customer_unique_id'].nunique().sort_values(ascending=False).head(10)
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.barplot(y=top_cities.index, x=top_cities.values, ax=ax)
    ax.set_xlabel('Customer Count')
    ax.set_ylabel('City')
    st.pyplot(fig)

with col2:
    st.subheader("Top 10 Best Selling Products")
    top_products = main_df.groupby('product_category_name_english')['order_id'].count().sort_values(ascending=False).head(10)
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.barplot(y=top_products.index, x=top_products.values, ax=ax)
    ax.set_xlabel('Number of Orders')
    ax.set_ylabel('Product Category')
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
    st.pyplot(fig)

# prompt: buat customer segmentation berdasarkan RFM tampilan sesuai tahun yang kepilih ,
#   2 kolom, kolom kiri pake metric average R, lalu bawahnya average F, average M .
# sampingnya piechart segmentasi VIP, Loyal, At risk, Churn. yang paling banyak kasih jarak dikit

import numpy as np
import matplotlib.cm as cm
# --- CUSTOMER SEGMENTATION ---
st.subheader("Customer Segmentation based on RFM")

# Calculate average R, F, and M
avg_r = main_df['Recency'].mean()
avg_f = main_df['Frequency'].mean()
avg_m = main_df['Monetary'].mean()


# Create columns for the metrics and pie chart
col1, col2 = st.columns([0.5,1.5])

with col1:
    st.metric("Average Recency (Days)", int(avg_r)) # cast to int for cleaner display
    st.metric("Average Frequency", int(avg_f)) # cast to int for cleaner display
    st.metric("Average Monetary Value", int(avg_m)) # cast to int for cleaner display

with col2:
    segment_counts = main_df['Segment'].value_counts()

    fig, ax = plt.subplots()
    num_segments = len(segment_counts)
    colors = cm.Blues(np.linspace(0.4, 1, num_segments))  # Adjust linspace for desired color range
    explode = [0] * num_segments  # Initialize with all zeros
    highest_segment_index = segment_counts.idxmax()  # Find the index of the highest segment
    explode[segment_counts.index.get_loc(highest_segment_index)] = 0.5  # Set distance for the highest segment

    ax.pie(segment_counts, labels=segment_counts.index, autopct='%1.1f%%',
           startangle=90, colors=colors)
    ax.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    st.pyplot(fig)

# prompt: streamlit 2 kolom yang bisa muncul sesuai tahun yang dipilih, trend analysis  transaksi harian plotnya garis bawahnya ada areanya, dan trend revenue harian


st.subheader("Trend Analysis")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Daily Transaction Trend")
    daily_transactions = main_df.groupby('order_purchase_timestamp')['order_id'].count().reset_index()
    daily_transactions = daily_transactions.rename(columns={'order_id': 'Transaction Count'})

    # Create the line plot with filled area
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.lineplot(x='order_purchase_timestamp', y='Transaction Count', data=daily_transactions, ax=ax)
    ax.fill_between(daily_transactions['order_purchase_timestamp'], daily_transactions['Transaction Count'], alpha=0.3)
    ax.set_xlabel("Date")
    ax.set_ylabel("Number of Transactions")
   # ax.set_title("Daily Transaction Trend",loc = 'center')
    plt.xticks(rotation=45)
    st.pyplot(fig)

with col2:
    st.subheader("Daily Revenue Trend")
    daily_revenue = main_df.groupby('order_purchase_timestamp')['price'].sum().reset_index()
    daily_revenue = daily_revenue.rename(columns={'price': 'Revenue'})

    # Create the line plot with filled area
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.lineplot(x='order_purchase_timestamp', y='Revenue', data=daily_revenue, ax=ax)
    ax.fill_between(daily_revenue['order_purchase_timestamp'], daily_revenue['Revenue'], alpha=0.3)
    ax.set_xlabel("Date")
    ax.set_ylabel("Revenue")
   # ax.set_title("Daily Revenue Trend", loc = 'center')
    plt.xticks(rotation=45)
    st.pyplot(fig)

col1, col2 = st.columns(2)

with col1:
    st.subheader("Monthly Transaction Trend")
    # Filter data by selected years
   # Convert 'order_purchase_timestamp' to datetime objects
    df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
    filtered_df = df[df['order_purchase_timestamp'].dt.year.isin(selected_years)]
    # Group by month and year and count transactions
    monthly_transactions = filtered_df.groupby(filtered_df['order_purchase_timestamp'].dt.to_period('M'))['order_id'].count().reset_index()
    monthly_transactions.columns = ['Month-Year', 'Transaction Count']
    monthly_transactions['Month-Year'] = monthly_transactions['Month-Year'].astype(str)

    fig, ax = plt.subplots(figsize=(8, 6))

    # Create line plot with filled area
    ax.plot(monthly_transactions['Month-Year'], monthly_transactions['Transaction Count'], marker='o', linestyle='-')
    ax.fill_between(monthly_transactions['Month-Year'], monthly_transactions['Transaction Count'], alpha=0.3)

    plt.xticks(rotation=90)
    ax.set_xlabel('Month')
    ax.set_ylabel('Transaction Count')
    st.pyplot(fig)

with col2:
    st.subheader("Monthly Revenue Trend")
    # Filter data by selected years
    filtered_df = df[df['order_purchase_timestamp'].dt.year.isin(selected_years)]

    # Group by month and year and sum revenue
    monthly_revenue = filtered_df.groupby(filtered_df['order_purchase_timestamp'].dt.to_period('M'))['price'].sum().reset_index()
    monthly_revenue.columns = ['Month-Year', 'Total Revenue']
    monthly_revenue['Month-Year'] = monthly_revenue['Month-Year'].astype(str)

    fig, ax = plt.subplots(figsize=(8, 6))

    # Create line plot with filled area
    ax.plot(monthly_revenue['Month-Year'], monthly_revenue['Total Revenue'], marker='o', linestyle='-')
    ax.fill_between(monthly_revenue['Month-Year'], monthly_revenue['Total Revenue'], alpha=0.3)

    plt.xticks(rotation=90)
    ax.set_xlabel('Month')
    ax.set_ylabel('Total Revenue')
    st.pyplot(fig)