# -*- coding: utf-8 -*-
"""dashboard1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHbEq46DPDHOK9c5Y1ySz7tc9UStomiY
"""

#pip install streamlit

#pip install babel

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import numpy as np
from babel.numbers import format_currency

sns.set(style='dark')

st.set_page_config(page_title="Brazilian E-commerce Dashboard",
                   page_icon=":bar_chart:", layout="wide")
hide_st_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            </style>
            """
st.markdown(hide_st_style, unsafe_allow_html=True)


# load dataframe
try:
    all_df = pd.read_csv("all_data.csv")
except FileNotFoundError:
    st.error("The 'all_data.csv' file was not found. Please upload the file.")
    st.stop()

# sidebar
with st.sidebar:
    st.image('Brazilianlogo.png')

    # Multiselect for years
    selected_years = st.multiselect(
        "Select Year(s)",
        options=[2016, 2017, 2018],
        default=[2016, 2017, 2018]  # Set default to all years
    )


# filtering data by year
if not pd.api.types.is_datetime64_any_dtype(all_df['order_purchase_timestamp']):
    all_df['order_purchase_timestamp'] = pd.to_datetime(all_df['order_purchase_timestamp'])

all_df['year'] = all_df['order_purchase_timestamp'].dt.year

main_df = all_df[all_df['year'].isin(selected_years)]


st.sidebar.header("Conclusion 2016-2018")
st.sidebar.markdown("""
1. 10 produk dengan jumlah penjualan terbanyak dalam periode 2016-2018, yaitu: bed_bath_table, furniture_decor,health_beauty, sports_leisure, computers_accessories, housewares, watches_gifts, garden_tools,telephony, auto.
 Produk terlaris didominasi produk rumah tangga dan dekorasi. Selain itu, health_beauty dan sports_leisure juga memiliki permintaan tinggi.

2. 10 Kota dan state yang memiliki pelanggan terbanyak pada 2016-2018, yaitu: Sao Paulo, Rio de Janeiro, Belo Horizonte, Brasilia, Curitiba, Campinas, Porto Alegre, Salvador, Guarulhos, Sao Bernardo do Campo

3. Tren jumlah transaksi dan total penjualan dari tahun 2016 hingga 2018:
- Tren transaksi penjualan terjadi pertumbuhan signifikan sejak 2017, mencapai puncaknya pada akhir 2017, dengan puncak tertinggi pada bulan November 2017.
- Tren total penjualan(revenue) menunjukkan pertumbuhan stabil hingga di akhir 2017, puncak pada bulan November 2017.

4. Penjual dengan total revenue tertinggi selama 2016-2018, berada di daerah guariba city, State of Sao Paulo dengan seller_id '4869f7a5dfa277a7dca6462dcf3b52b2'. Penjual tersebut memiliki kategori produk terlaris yaitu : Auto, Watches & Gifts
, Health & Beauty, Cool Stuff, Computers Accessories, Electronics, Audio, Sports & Leisure, Telephony, Consoles & Games dengan total revenue 229472.63.

5. Berdasarkan analisis teks dari ulasan pelanggan tahun 2016-2018, komentar  yang paling sering disebut dalam ulasan yaitu kata-kata seperti "Muito bom" (Sangat baik), "Bom" (Baik), "Ótimo" (Luar biasa), dan "Recomendo" (Saya rekomendasikan)

6. analisis RFM untuk mengidentifikasi pelanggan yang VIP, Loyal, At Risk to Churn, dan Churn berdasarkan transaksi terakhir menunjukkan bahwa:
-  VIP Customers adalah pelanggan dengan transaksi terbaru, sering berbelanja, dan memiliki nilai transaksi tinggi. Mereka harus dijaga dengan program eksklusif.
- Loyal Customers sering berbelanja tetapi mungkin tidak dalam waktu dekat. Penawaran khusus dapat meningkatkan keterlibatan mereka secara berlanjut.
- At Risk to Churn adalah pelanggan yang dulunya aktif tetapi mulai jarang berbelanja. Strategi re-engagement diperlukan untuk menarik mereka kembali.
- Churned Customers tidak bertransaksi dalam waktu lama. Promosi khusus atau diskon besar bisa menjadi cara untuk mengaktifkan mereka kembali.
- Sao Paulo dan Rio de Janeiro memiliki jumlah churn tertinggi
- Churn pada tahun 2017- 2018 cukup tinggi.
- Churn customer mendominasi dengan 59.9%, menunjukkan bahwa lebih dari setengah pelanggan telah berhenti menggunakan layanan.
""")

st.markdown(
    """
    Hello, C - Level ! :smile: :wave:
    """
)
st.header('Brazilian E-Commerce Dashboard :bar_chart:')
#
st.markdown("---")

df = pd.read_csv('all_data.csv')

# Metric
total_customers = main_df['customer_unique_id'].nunique()
total_sellers = main_df['seller_id'].nunique()
total_transactions = len(main_df)
total_revenue = main_df['price'].sum()
formatted_revenue = format_currency(total_revenue, 'R$', locale='pt_BR')

# Create columns
col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Customers", total_customers)
col2.metric("Total Sellers", total_sellers)
col3.metric("Total Transactions", total_transactions)
col4.metric("Total Revenue (R$)", total_revenue)

#  top 10 best selling products
st.subheader("Top 10 Best Selling Products")

top_products = main_df.groupby('product_category_name_english')['order_id'].count().sort_values(ascending=False).head(10)

fig, ax = plt.subplots(figsize=(16, 6))

# barplot
sns.barplot(y=top_products.index, x=top_products.values, ax=ax)
ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
ax.set_xlabel('Product Category')
ax.set_ylabel('Number of Orders')
ax.set_title(f'Top 10 Best Selling Products ({", ".join(map(str, selected_years))})')
st.pyplot(fig)

col1, col2 = st.columns(2)
# top10 cities by cust
with col1:
    st.subheader("Top 10 Cities by Customers")
    top_cities = main_df.groupby('customer_city')['customer_unique_id'].nunique().sort_values(ascending=False).head(10)
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.barplot(y=top_cities.index, x=top_cities.values, ax=ax)
    ax.set_xlabel('Customer Count')
    ax.set_ylabel('City')
    st.pyplot(fig)

#top10 products
with col2:
    st.subheader("Top 10 Best Selling Products")
    top_products = main_df.groupby('product_category_name_english')['order_id'].count().sort_values(ascending=False).head(10)
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.barplot(y=top_products.index, x=top_products.values, ax=ax)
    ax.set_xlabel('Number of Orders')
    ax.set_ylabel('Product Category')
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
    st.pyplot(fig)

import matplotlib.cm as cm

# customer segmentation
st.subheader("Customer Segmentation based on RFM")

# average R, F, and M
avg_r = main_df['Recency'].mean()
avg_f = main_df['Frequency'].mean()
avg_m = main_df['Monetary'].mean()


col1, col2 = st.columns([0.5,1.5])
#display ave RFM
with col1:
    st.metric("Average Recency (Days)", int(avg_r))
    st.metric("Average Frequency", int(avg_f))
    st.metric("Average Monetary Value", int(avg_m))

#display piechart segmentasi VIP, Loyal, At Risk, Churn
with col2:
    segment_counts = main_df['Segment'].value_counts()

    fig, ax = plt.subplots()
    num_segments = len(segment_counts)
    colors = cm.Blues(np.linspace(0.4, 1, num_segments))
    ax.pie(segment_counts, labels=segment_counts.index, autopct='%1.1f%%',
           startangle=90, colors=colors)
    ax.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    st.pyplot(fig)

st.subheader("Trend Analysis")

col1, col2 = st.columns(2)
#daily transaction tren
with col1:
    st.subheader("Daily Transaction Trend")
    daily_transactions = main_df.groupby('order_purchase_timestamp')['order_id'].count().reset_index()
    daily_transactions = daily_transactions.rename(columns={'order_id': 'Transaction Count'})

    # line plot
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.lineplot(x='order_purchase_timestamp', y='Transaction Count', data=daily_transactions, ax=ax)
    ax.fill_between(daily_transactions['order_purchase_timestamp'], daily_transactions['Transaction Count'], alpha=0.3)
    ax.set_xlabel("Date")
    ax.set_ylabel("Number of Transactions")
    plt.xticks(rotation=45)
    st.pyplot(fig)

# Daily revenue trend

with col2:
    st.subheader("Daily Revenue Trend")
    daily_revenue = main_df.groupby('order_purchase_timestamp')['price'].sum().reset_index()
    daily_revenue = daily_revenue.rename(columns={'price': 'Revenue'})

    # lineplot
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.lineplot(x='order_purchase_timestamp', y='Revenue', data=daily_revenue, ax=ax)
    ax.fill_between(daily_revenue['order_purchase_timestamp'], daily_revenue['Revenue'], alpha=0.3)
    ax.set_xlabel("Date")
    ax.set_ylabel("Revenue")
    plt.xticks(rotation=45)
    st.pyplot(fig)

# mothly trend analysis
col1, col2 = st.columns(2)

#transaction trend
with col1:
    st.subheader("Monthly Transaction Trend")

    df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
    filtered_df = df[df['order_purchase_timestamp'].dt.year.isin(selected_years)]
    monthly_transactions = filtered_df.groupby(filtered_df['order_purchase_timestamp'].dt.to_period('M'))['order_id'].count().reset_index()
    monthly_transactions.columns = ['Month-Year', 'Transaction Count']
    monthly_transactions['Month-Year'] = monthly_transactions['Month-Year'].astype(str)

    fig, ax = plt.subplots(figsize=(8, 6))

    # Create line plot
    ax.plot(monthly_transactions['Month-Year'], monthly_transactions['Transaction Count'], marker='o', linestyle='-')
    ax.fill_between(monthly_transactions['Month-Year'], monthly_transactions['Transaction Count'], alpha=0.3)

    plt.xticks(rotation=90)
    ax.set_xlabel('Month')
    ax.set_ylabel('Transaction Count')
    st.pyplot(fig)

#revenue trend
with col2:
    st.subheader("Monthly Revenue Trend")

    filtered_df = df[df['order_purchase_timestamp'].dt.year.isin(selected_years)]

    # Group by month and year and sum revenue
    monthly_revenue = filtered_df.groupby(filtered_df['order_purchase_timestamp'].dt.to_period('M'))['price'].sum().reset_index()
    monthly_revenue.columns = ['Month-Year', 'Total Revenue']
    monthly_revenue['Month-Year'] = monthly_revenue['Month-Year'].astype(str)

    fig, ax = plt.subplots(figsize=(8, 6))

    # Create line plot
    ax.plot(monthly_revenue['Month-Year'], monthly_revenue['Total Revenue'], marker='o', linestyle='-')
    ax.fill_between(monthly_revenue['Month-Year'], monthly_revenue['Total Revenue'], alpha=0.3)

    plt.xticks(rotation=90)
    ax.set_xlabel('Month')
    ax.set_ylabel('Total Revenue')
    st.pyplot(fig)